### ISSUE TITLE
Inject file set controller behaviors rather than override file set controller class

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#273] opened 2016-12-12 20:58 UTC
https://github.com/projecthydra-labs/geo_concerns/blob/master/lib/generators/geo_concerns/install_generator.rb#L47-L50

https://github.com/projecthydra-labs/geo_concerns/blob/master/lib/generators/geo_concerns/templates/controllers/curation_concerns/file_sets_controller.rb#L3-L5

**Comment by afred** [comment] 2017-02-17 21:45
dupe of #291

**Closed** 2017-02-17 21:44 UTC
Labels: Plugins
